# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ca0ac5dc42270e2b4854a06f18d48b46dc6609e5293832b687dcc2e473b735647fff10675fdb6fcaa638f7cbe3f4a2ed3f30c50891e57322aab9f5d5a865d6d

test:
  secret_key_base: dd457a3ce78d09e9026ee012960376bc66c942b34af324d740afb5d761ce1c6c9de0e6823af925299de3e8766951302a01d138113f711bf79f3f2d5a5e74537a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
